# Generated by Django 4.2.1 on 2023-06-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
